%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.8

-ifndef(myuser).
-define(myuser, true).

-define(myuser_gpb_version, "3.26.8").

-ifndef('JOB_PB_H').
-define('JOB_PB_H', true).
-record(job,
        {company,                       % = 1, int32
         title                          % = 2, string (optional)
        }).
-endif.

-ifndef('IDENTITY_PB_H').
-define('IDENTITY_PB_H', true).
-record(identity,
        {name,                          % = 1, string
         family = [],                   % = 2, [string]
         age                            % = 3, int32 (optional)
        }).
-endif.

-ifndef('MYUSER_PB_H').
-define('MYUSER_PB_H', true).
-record(myuser,
        {id,                            % = 1, {msg,identity}
         sex,                           % = 2, {enum,enum_sex} (optional)
         job = []                       % = 3, [{msg,job}]
        }).
-endif.

-endif.
